l1_url = "https://solana-devnet.g.alchemy.com/v2/pw2wvRbDIcTAlOi73eibtHiCMG9UX3al"
l2_url = "http://13.215.160.229:8899"
watched_account = "4Wa9Qm19cjxP3cjoS8GNFY9zFQK6TWMLbmN6PDWZq3a7"
wallet_path = "~/.config/solana/id.json"
l1_program_id = "GFvvYUqbgRheG4K9MgGsnYGX7UWJNEVr5hgksXT1xeuk"
l2_program_id = "7HVZ6xxrdeVdWs5jDJoJBBxqv4gm4shM8SCtwxSsmgSb"
nonce_account = "HwjL8GnLM59LEDrodfemRmXpPPdqw4ztkSwXRb1NDKMF"
